export const APP_UPDATE_SEARCHED_DATA = 'APP/UPDATE/SEARCHED/DATA';
export const APP_UPDATE_SEARCH_TEXT = 'APP/UPDATE/SEARCH/TEXT';
export const APP_UPDATE_SEARCH_KEY = 'APP/UPDATE/SEARCH/KEY';
export const APP_UPDATE_MODAL_VISIBILITY = 'APP/UPDATE/MODAL/VISIBILITY';
export const SORT_BY_NAME = 'SORT/BY/NAME';
