export const SUBCAT_GET_HANDLER = 'SUBCAT/GET/HANDLER';
export const PRODUCT_GET_HANDLER = 'PRODUCT/GET/HANDLER';
export const SUBCAT_REFRESH_HANDLER = 'SUBCAT/REFRESH/HANDLER';
export const APP_SEARCHBAR_RESET = 'APP/SEARCHBAR/RESET';
export const RESET_REDUCER = 'RESET/REDUCER';
export const UPDATE_PRODUCT_DATA = 'UPDATE/PRODUCT/DATA';
